version: '3.8'

services:
  wildfly1:
    image: quay.io/wildfly/wildfly:latest-jdk21
    environment:
      - JGROUPS_CLUSTER_NAME=wildfly-cluster
      - JGROUPS_DISCOVERY_PROTOCOL=DNS_PING
      - JGROUPS_DISCOVERY_PROPERTIES=dns_query=tasks.wildfly1,tasks.wildfly2
      - CACHE_OWNERS=2
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./FannyWeb-1.1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/FannyWeb-1.1.0-SNAPSHOT.war
      - ./jboss_conf/fanny/custom-standalone-ha.xml:/opt/jboss/wildfly/standalone/configuration/standalone-ha.xml
    networks:
      - wildfly-cluster

  wildfly2:
    image: quay.io/wildfly/wildfly:latest-jdk21
    environment:
      - JGROUPS_CLUSTER_NAME=wildfly-cluster
      - JGROUPS_DISCOVERY_PROTOCOL=DNS_PING
      - JGROUPS_DISCOVERY_PROPERTIES=dns_query=tasks.wildfly1,tasks.wildfly2
      - CACHE_OWNERS=2
    ports:
      - "8081:8080"
      - "9991:9990"
    volumes:
      - ./FannyWeb-1.1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/FannyWeb-1.1.0-SNAPSHOT.war
      - ./jboss_conf/fanny/custom-standalone-ha.xml:/opt/jboss/wildfly/standalone/configuration/standalone-ha.xml
    networks:
      - wildfly-cluster

networks:
  wildfly-cluster:
    driver: bridge
