version: "3.8"

services:
  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk21
    volumes:
      - ./fanny.war:/opt/jboss/wildfly/standalone/deployments/fanny.war
    environment:
      JBOSS_MODULESYSTEM_PROP_org.wildfly.security.auth.realm.JBossRealm.password-hashing: CLEAR
      JBOSS_MODULESYSTEM_PROP_org.wildfly.security.auth.mechanism.http.FormBasedAuthenticationMechanism.require-login: false
    user: jboss
    ports:
      - "8080:8080"